# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NDIw5ZDSCl7CtoC-QVflkvB0Drb76GP0
"""

#FORMULÁRIO DE CADASTRO

name  = input('DIGITE SEU NOME')
age = int(input("digite sua idade"))
experience =  input("digite sua experiencia com informatica")
gen =  input("digite seu genêro")
#indentação === organização do código em python


#OR   OU

if age >= 18 or age <= 65:
    print("você pode votar")
else:
    print("você não pode votar")


if experience == "excel" and age == 20:
    print("Selecionado(a)")
else:
    print('Você não foi selecionado')




#!=   DIFERENTE

if age  !=  18:
  print(" É candidato para a vaga ")
elif age == 16:
  print("menor aprendiz")
else:
   print("Não foi selecionado")



if(age == 20):
    print("maior de idade")



#NOT  NÃO

language  =  "Inglês"

if not language  == "Português":
   print("Contratado ")
else:
   print("Não selecionado")

110